trigger: none

name: $(version)

variables:
- name: ImagePrefix
  value: "mvx_prod_erp_$(version)"

pool: 
  name: Default

steps:

  #- task: Bash@3
  #  inputs:
  #    targetType: 'inline'
  #    script: |
  #      export PACKER_RELEASE="1.7.2"
  #      cd /tmp/
  #      wget https://releases.hashicorp.com/packer/${PACKER_RELEASE}/packer_${PACKER_RELEASE}_linux_amd64.zip
  #      unzip packer_${PACKER_RELEASE}_linux_amd64.zip
  #      sudo mv packer /usr/local/bin
  - task: Bash@3
    inputs:
      workingDirectory: MVX.IAC/PACKER/vm-erp
      displayName: 'Check files'
      targetType: 'inline'
      script: |
        ls -l

  - task: Bash@3
    inputs:
      workingDirectory: MVX.IAC/PACKER/vm-erp
      targetType: 'inline'
      script: |
        export PKR_VAR_client_id=3868b7a5-b6df-4632-82f5-80b8d5406c99
        export PKR_VAR_client_secret=vjgUE._s_.LZnQ28h8ybEMHVWM85zTd~WK
        export PKR_VAR_subscription_id=6e6145fd-2644-4673-96f0-a813a725ca4c
        export PKR_VAR_tenant_id=c58f8565-7ab4-440f-84f2-dd75f3745a69
        packer build -force  \
        -var "managed_image_prefix=$(ImagePrefix)" \
        -var "gallery_name=sharedgallery_microvix_production" \
        -var "gallery_managed_image_prefix=mvx_prod_erp" \
        -var "managed_image_resource_group_name=mvxprd-templates" \
        -var "image_version=$(version)" .
    displayName: 'packer build'
