name: Create Image for Nginx with Packer - 3.0.$(Rev:r)

trigger: none

pool:
  vmImage: ubuntu-latest

resources: # Download Repo of Devops-Microvix for use template Nginx Config
  repositories:
  - repository: EnvBuilder
    type: git
    name: DevOps/EnvBuilder    
    ref: main

variables:
  WORK_PATH: "Packer/vm/nginx"
  ImageName: "NGINX"
  Environment: "MVX"

stages:
- stage: Development
  variables: 
    - group: PACKER_DEV

  jobs:
  - job: Packer
    steps:
      - checkout: self
      - checkout: EnvBuilder
        displayName: Checkout Git Repositories

      - task: Bash@3
        inputs:
          workingDirectory: $(System.DefaultWorkingDirectory)templates/
          targetType: "inline"
          script: |
            ls -lR
        displayName: List Files Sytem Default workingDirectory

      - template: ci-main.yml # Template utilizado para execução das tarefas da pipeline
        parameters:
          WORK_PATH: $(WORK_PATH)
          ManagedImagePrefix: "$(Environment)_DEV_$(ImageName)"
          PackerVarFile: "development.pkrvars.hcl"
          AzureResourceGroupTemplate: "rg-mvx-development-shared-eastus"
          TempAzureResouceGroup: "rg-mvx-development-shared-eastus"
          # imageVersion: $(Build.BuildNumber)
          imageVersion: "1.0.0"
          CLIENT_ID: $(CLIENT_ID)
          CLIENT_SECRET: $(CLIENT_SECRET)
          SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
          TENANT_ID: $(TENANT_ID)

# - stage: Production
#   variables: 
#     - group: PACKER_PROD
  
#   jobs:
#   - job: Packer
#     steps:
#     - template: ci-main.yml # Template utilizado para execução das tarefas da pipeline
      
#       parameters:
#         WORK_PATH: $(WORK_PATH)
#         ManagedImagePrefix: "$(Environment)_prod_$(ImageName)"
#         PackerVarFile: "prod.pkrvars.hcl"
#         AzureResourceGroupTemplate: "rg-mvx-prod-shared-eastus"
#         TempAzureResouceGroup: "rg-mvx-prod-packer-temp"
#         imageVersion: $(Build.BuildNumber)
#         CLIENT_ID: $(CLIENT_ID)
#         CLIENT_SECRET: $(CLIENT_SECRET)
#         SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
#         TENANT_ID: $(TENANT_ID)