trigger: none
name: 1.0.$(Rev:r)

variables:
  - group: PACKER
  - name: PACKER_RELEASE
    value: "1.8.4"
  #
  # DEFINE ON PIPELINE ---> KEY : VALUE
  #
  # ManagedImagePrefix: mvx_prod_erp_$(version)
  # AzureGalleryName: sharedgallery_microvix_production
  # AzureGalleryManagedImagePrefix: mvx_prod_erp
  # AzureResourceGroupTemplate: mvxprd-templates

pool:
  #name: DevOps-VMSS
  vmImage: ubuntu-latest

steps:
  - task: Bash@3
    inputs:
      targetType: "inline"
      script: |
        wget https://releases.hashicorp.com/packer/${PACKER_RELEASE}/packer_${PACKER_RELEASE}_linux_amd64.zip
        unzip packer_${PACKER_RELEASE}_linux_amd64.zip
        sudo mv packer /usr/local/bin
    displayName: PACKER - INSTALL

  - task: Bash@3
    inputs:
      workingDirectory: $(WORK_PATH)
      targetType: "inline"
      script: |
        ls -lR
    displayName: Checking - List Files

  - task: Bash@3
    inputs:
      workingDirectory: $(WORK_PATH)
      targetType: "inline"
      script: |
        echo "MANAGED_IMAGE_PREFIX " $MANAGED_IMAGE_PREFIX
        echo "Image_version :" $(Build.BuildNumber)
        echo "AZUREGALLERYNAME " $AZUREGALLERYNAME
        echo "AZURE_RESOURCE_GROUP_TEMPLATE: " $AZURE_RESOURCE_GROUP_TEMPLATE
        echo "Azure Authentication"
        echo "Client ID: " $CLIENT_ID
        echo "Subscription ID: " $SUBSCRIPTION_ID
        echo "Tenant ID: " $TENANT_ID
    displayName: Checking - Variables

  - task: Bash@3
    inputs:
      workingDirectory: $(WORK_PATH)
      targetType: "inline"
      script: |
        packer build -force  \
          -var "managed_image_prefix=$(MANAGED_IMAGE_PREFIX)" \
          -var "gallery_managed_image_prefix=$(MANAGED_IMAGE_PREFIX)" \
          -var "gallery_name=$(AZUREGALLERYNAME)" \
          -var "managed_image_resource_group_name=$(AZURE_RESOURCE_GROUP_TEMPLATE)" \
          -var "image_version=$(Build.BuildNumber)" .
    env:
      PKR_VAR_client_id: $(CLIENT_ID)
      PKR_VAR_client_secret: $(CLIENT_SECRET)
      PKR_VAR_subscription_id: $(SUBSCRIPTION_ID)
      PKR_VAR_tenant: $(TENANT_ID)
    displayName: PACKER - BUILD
