trigger: none
name: 1.0.$(Rev:r)

variables:
#- name: ManagedImagePrefix
  #value: "mvx_prod_erp_$(version)"
#- name: AzureGalleryName
  # sharedgallery_microvix_production
#- name: AzureGalleryManagedImagePrefix
  # mvx_prod_erp
#- name: AzureResourceGroupTemplate
  # mvxprd-templates
- name: PACKER_RELEASE
  value: '1.8.2'
#- name: WORK_PATH

pool: 
  vmImage: 'ubuntu-latest'

steps:

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        wget https://releases.hashicorp.com/packer/${PACKER_RELEASE}/packer_${PACKER_RELEASE}_linux_amd64.zip
        unzip packer_${PACKER_RELEASE}_linux_amd64.zip
        sudo mv packer /usr/local/bin

  - task: Bash@3
    inputs:
      workingDirectory: vm-erp
      targetType: 'inline'
      script: |
        ls -lR

  - task: Bash@3
    inputs:
      workingDirectory:  vm-erp
      targetType: 'inline'
      script: |
            packer build -force  \
              -var "managed_image_prefix=$(MANAGED_IMAGE_PREFIX)_$(NAME)" \
              -var "gallery_name=$(AZUREGALLERYNAME)" \
              -var "gallery_managed_image_prefix=$(AZURE_GALLERY_MANAGEDIMAGE_PREFIX)" \
              -var "managed_image_resource_group_name=$(AZURE_RESOURCE_GROUP_TEMPLATE)" \
              -var "image_version=$(Build.BuildNumber)" .
    env:
     PKR_VAR_client_id: $(CLIENT_ID)
     PKR_VAR_client_secret: $(CLIENT_SECRET)
     PKR_VAR_subscription_id: $(SUBSCRIPTION_ID)
     PKR_VAR_tenant: $(TENANT_ID)
    displayName: 'packer build'
