trigger: none
name: 1.0.$(Rev:r)


variables:
- name: ManagedImagePrefix
  #value: "mvx_prod_erp_$(version)"
- name: AzureGalleryName
  # sharedgallery_microvix_production
- name: AzureGalleryManagedImagePrefix
  # mvx_prod_erp
- name: AzureResourceGroupTemplate
  # mvxprd-templates
- name: PACKER_RELEASE
  value: '1.8.2'

pool: 
  name: Default

steps:

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        wget https://releases.hashicorp.com/packer/${PACKER_RELEASE}/packer_${PACKER_RELEASE}_linux_amd64.zip
        unzip packer_${PACKER_RELEASE}_linux_amd64.zip
        sudo mv packer /usr/local/bin
  
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
            packer build -force  \
              -var "managed_image_prefix=$(ManagedImagePrefix)" \
              -var "gallery_name=$(AzureGalleryName)" \
              -var "gallery_managed_image_prefix=$(AzureGalleryManagedImagePrefix)" \
              -var "managed_image_resource_group_name=$(AzureResourceGroupTemplate)" \
              -var "image_version=$(build.version)" .
      workingDirectory: MVX.IAC/PACKER/vm-erp
      env:
        TF_IN_AUTOMATION: true
        PKR_VAR_client_id: $(tf-sp-clientId)
        PKR_VAR_client_secret: $(tf-sp-clientSecret)
        PKR_VAR_subscription_id: $(tf-sp-subscriptionId)
        PKR_VAR_tenant: $(tf-sp-tenantId)
    displayName: 'packer build'
