vm_size = "standard_b2ms"
managed_image_prefix = "mvx_dev_nginx"
image_version = "1.0.0"
managed_image_resource_group_name = "rg-mvx-development-shared-eastus"
build_resource_group_name = "rg-mvx-development-packer-temp"